### ISSUE TITLE
🚧 Refresh this repository

### ISSUE THREAD

**Issue by xunleii** [xunleii/terraform-module-k3s#140]
This project is a little old and needs to be refreshed.

---
### Definition of done
- [x] Update the README with ~~#132~~ and #136 informations
- [x] Include existing example inside the README to avoid non-working example (like in #136) 
- [x] Add some automatisation like stale-bot
- [x] Add pre-filled template for issue
- [x] Add some security checks for TF
- [x] Add example for at least one _big_ cloud provider (#43)

_NOTE¹: I remove the #132 on this issue scope because of its complexity; it's not just a simple documentation but requires more investigation too_
_NOTE²: I remove the `how to contribute` task waiting the #133 to be implemented_
